-- Put your own information into the database. (You may used falsified 
-- information for anything you feel is too personal to share, just 
-- make sure your first and last name are the same as what we see 
-- in Canvas.)
